//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAp_L50_MVC_JQuery_EF_DDN_26523.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblState
    {
        public int sid { get; set; }
        public Nullable<int> cid { get; set; }
        public string sname { get; set; }
    }
}
